#
# Makefile for the fingerprint drivers.
#

obj-y	+=  fp_drv/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF32X8_QSEE)	+= goodix_3208qsee/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF316M)	+= goodix_316m/
obj-$(CONFIG_FINGERPRINT_ELAN_96SA_QSEE)		+= elan_96sa/
obj-$(CONFIG_FINGERPRINT_ELAN_519C_QSEE)		+= elan_519c/
obj-$(CONFIG_FINGERPRINT_SILEAD_6163_QSEE)		+= silead_6163/
obj-$(CONFIG_FINGERPRINT_CHIPONE_7152_QSEE)		+= chipone_7152qsee/

